
from fastapi import FastAPI 
from sqlalchemy import create_engine, text
from fastapi.middleware.cors import CORSMiddleware
import os
import pandas as pd
import numpy as np
from fastapi.responses import JSONResponse
from datetime import datetime
from fastapi.encoders import jsonable_encoder
import uvicorn
app = FastAPI()

# Permitir solicitudes desde Streamlit
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://10.10.21.53:8501"],  # ⚠️ Restringe esto a tu dominio en producción
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Crear engine con URL del entorno (usa la misma variable 'ebs12')
DATABASE_URL = os.getenv("ebs12")
engine = create_engine(DATABASE_URL)

@app.get("/datos")
def obtener_datos():
    query = """
    
    Select 
	ooha.HEADER_ID,
	RCTA.PURCHASE_ORDER		AS OCC,
	OOHA.ORDER_NUMBER		AS [No PEDIDO ORACLE],
	HAOU.NAME				AS ALMACEN,
	HPSF.PARTY_SITE_NUMBER	AS CLIENTE_FACTURACION,
    HPS.PARTY_SITE_NUMBER	AS CLIENTE_ENTREGA,
    HP.PARTY_NAME			AS CLIENTE,
	HP.Party_ID				AS Party_ID,
	client.Formato			AS FORMATO,
	client.Canal			AS CANAL,
	OOHA.PRICING_DATE		AS [FECHA OC],
	OOHA.ATTRIBUTE6			AS [FECHA ENTREGA],
	OOHA.ATTRIBUTE1			AS [FECHA CANCELACION],
	OOLA.LINE_NUMBER		AS LINEA,
	MSIB.SEGMENT1			AS SKU,
	MSIB.DESCRIPTION		AS DESCRIPCION,
	pro.[Unidad de Negocio]	AS FAMILIA,
	PRO.[Factor Conversion]	AS [Factor Conversion],
	Muc.CONVERSION_RATE		AS [Tarimas a cajas],
	OOLA.ORDER_QUANTITY_UOM	AS UDM,
	ISNULL(Muc.CONVERSION_RATE,	1) * (COALESCE(RCTL.QUANTITY_CREDITED, 0) + COALESCE(RCTL.QUANTITY_INVOICED, 0)) AS [CANTIDAD FACTURADA],
	ISNULL(Muc.CONVERSION_RATE,	1) * (OOLA.ORDERED_QUANTITY)	AS [CANTIDAD ORDENADA],
	ISNULL(Muc.CONVERSION_RATE,	1) * (OOLA.CANCELLED_QUANTITY)	AS	[CANTIDAD CANCELADA],
	--ISNULL(FND.LOOKUP_CODE, FND.LOOKUP_CODE) AS [CODIGO MOTIVO],
	--ISNULL(FND.DESCRIPTION, FND.DESCRIPTION) AS [MOTIVO CANCELACION],
	FND.LOOKUP_CODE AS CODIGO_MOTIVO,
	FND.DESCRIPTION AS MOTIVO_CANCELACION,
 
	TL.NAME					AS [TIPO PEDIDO],
	OOHA.CREATION_DATE		AS [FECHA CREACION],
	RCTA.TRX_NUMBER			AS FACTURA,
	RCTA.TRX_DATE			AS [FECHA FACTURA]
 
 
 
from
RA_CUSTOMER_TRX_ALL RCTA
LEFT JOIN RA_CUST_TRX_TYPES_ALL			RCTTA	ON RCTTA.CUST_TRX_TYPE_ID = RCTA.CUST_TRX_TYPE_ID  
LEFT JOIN RA_CUSTOMER_TRX_LINES_ALL		RCTL	ON RCTL.CUSTOMER_TRX_ID = RCTA.CUSTOMER_TRX_ID 
LEFT JOIN OE_ORDER_LINES_ALL			OOLA	ON OOLA.LINE_ID = RCTL.INTERFACE_LINE_ATTRIBUTE6
LEFT JOIN OE_ORDER_HEADERS_ALL			OOHA	ON OOHA.HEADER_ID = OOLA.HEADER_ID
LEFT JOIN OE_TRANSACTION_TYPES_TL		TL		ON TL.TRANSACTION_TYPE_ID = OOHA.ORDER_TYPE_ID and TL.LANGUAGE = 'ESA'
LEFT JOIN MTL_SYSTEM_ITEMS_B			MSIB	ON MSIB.INVENTORY_ITEM_ID	= RCTL.INVENTORY_ITEM_ID AND MSIB.ORGANIZATION_ID = 101
LEFT JOIN HR_ALL_ORGANIZATION_UNITS		HAOU	ON HAOU.ORGANIZATION_ID = OOLA.SHIP_FROM_ORG_ID
LEFT JOIN HZ_CUST_SITE_USES_ALL			HCSUA	ON HCSUA.SITE_USE_ID = OOHA.SHIP_TO_ORG_ID 
LEFT JOIN HZ_CUST_ACCT_SITES_ALL		HCAS	ON HCAS.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID 
LEFT JOIN HZ_PARTY_SITES				HPS		ON HPS.PARTY_SITE_ID = HCAS.PARTY_SITE_ID
left JOIN HZ_PARTIES					HP		ON HP.PARTY_ID = HPS.PARTY_ID 
left JOIN HZ_CUST_SITE_USES_ALL			HCSUAF	ON HCSUAF.SITE_USE_ID = OOHA.INVOICE_TO_ORG_ID 
left JOIN HZ_CUST_ACCT_SITES_ALL		HCASF   ON HCASF.CUST_ACCT_SITE_ID = HCSUAF.CUST_ACCT_SITE_ID 
Left JOIN HZ_PARTY_SITES				HPSF    ON HPSF.PARTY_SITE_ID = HCASF.PARTY_SITE_ID 
left JOIN HZ_PARTIES					HPF		ON HPF.PARTY_ID = HPSF.PARTY_ID 
left JOIN HZ_CUST_ACCOUNTS				HCA		ON HCA.CUST_ACCOUNT_ID = HCAS.CUST_ACCOUNT_ID 
Left Join [PICO_VENTAS].[dbo].[clientes] client On client.[No_] = HPS.PARTY_SITE_NUMBER
left Join [PICO_VENTAS].[dbo].[productos] pro 	ON pro.[No_] = MSIB.SEGMENT1
Left Join MTL_UOM_CONVERSIONS			MUC		On Muc.[UOM_CODE] = RCTL.UOM_CODE and Muc.[INVENTORY_ITEM_ID] = RCTL.[INVENTORY_ITEM_ID]
LEFT JOIN FND_LOOKUP_VALUES				FND		ON FND.LOOKUP_CODE= RCTA.REASON_CODE AND FND.LANGUAGE = 'ESA' AND FND.VIEW_APPLICATION_ID = RCTA.PROGRAM_APPLICATION_ID AND FND.DESCRIPTION IS NOT NULL
 
 
 
where (RCTL.QUANTITY_CREDITED IS NOT NULL OR RCTL.QUANTITY_INVOICED IS NOT NULL)
and CONVERT(DATETIME, CONVERT(DATE, OOHA.CREATION_DATE)) > '01-01-2022'

and RCTA.ORG_ID = 81
AND OOHA.ORG_ID = 81
 
 
UNION
 
 

 
SELECT DISTINCT 
	OOHA.HEADER_ID,
	OOLA.CUST_PO_NUMBER			AS		OCC,
	OOHA.ORDER_NUMBER			AS		[No PEDIDO ORACLE],
	HAOU.NAME					AS		ALMACEN,
	HPSF.PARTY_SITE_NUMBER		AS		CLIENTE_FACTURACION,
    HPS.PARTY_SITE_NUMBER		AS		CLIENTE_ENTREGA,
    HP.PARTY_NAME				AS		CLIENTE,
	HP.Party_ID					AS		Party_ID,
	client.Formato				AS		FORMATO,
	client.Canal				AS		CANAL,
	OOHA.PRICING_DATE			AS		[FECHA OC],
	OOHA.ATTRIBUTE6				AS		[FECHA ENTREGA],
	OOHA.ATTRIBUTE1				AS		[FECHA CANCELACION],
	OOLA.LINE_NUMBER			AS		LINEA,
	MSIB.SEGMENT1				AS		SKU,
	MSIB.DESCRIPTION			AS		DESCRIPCION,
	pro.[Unidad de Negocio]		AS		FAMILIA,
	PRO.[Factor Conversion]		AS		[Factor Conversion],
	Muc.CONVERSION_RATE			AS [Tarimas a cajas],
	OOLA.ORDER_QUANTITY_UOM	AS UDM,
	NULL						AS		[CANTIDAD FACTURADA],
	NULL						AS		[CANTIDAD ORDENADA],
	ISNULL(Muc.CONVERSION_RATE,	1) * (OOLA.CANCELLED_QUANTITY)	AS	[CANTIDAD CANCELADA],
	FND.LOOKUP_CODE				AS		[CODIGO MOTIVO],
	FND.DESCRIPTION				AS		[MOTIVO CANCELACION],
 
 
 
	TL.NAME						AS		[TIPO PEDIDO],
	OOLA.CREATION_DATE			AS		[FECHA_CREACION],
	NULL						AS		FACTURA,
	NULL						AS		[FECHA FACTURA]
 
 

 
 
FROM OE_ORDER_LINES_ALL OOLA
LEFT JOIN OE_ORDER_HEADERS_ALL			OOHA	ON OOHA.HEADER_ID = OOLA.HEADER_ID
LEFT JOIN MTL_SYSTEM_ITEMS_B			MSIB	ON MSIB.INVENTORY_ITEM_ID	= OOLA.INVENTORY_ITEM_ID AND MSIB.ORGANIZATION_ID = 101
left JOIN OE_TRANSACTION_TYPES_TL		TL		ON TL.TRANSACTION_TYPE_ID = OOHA.ORDER_TYPE_ID and TL.LANGUAGE = 'ESA'
LEFT JOIN HR_ALL_ORGANIZATION_UNITS		HAOU	ON HAOU.ORGANIZATION_ID = OOLA.SHIP_FROM_ORG_ID
LEFT JOIN HZ_CUST_SITE_USES_ALL			HCSUA	ON HCSUA.SITE_USE_ID = OOHA.SHIP_TO_ORG_ID 
LEFT JOIN HZ_CUST_ACCT_SITES_ALL		HCAS	ON HCAS.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID 
LEFT JOIN HZ_PARTY_SITES				HPS		ON HPS.PARTY_SITE_ID = HCAS.PARTY_SITE_ID
left JOIN HZ_PARTIES					HP		ON HP.PARTY_ID = HPS.PARTY_ID 
left JOIN HZ_CUST_SITE_USES_ALL			HCSUAF	ON HCSUAF.SITE_USE_ID = OOHA.INVOICE_TO_ORG_ID 
left JOIN HZ_CUST_ACCT_SITES_ALL		HCASF   ON HCASF.CUST_ACCT_SITE_ID = HCSUAF.CUST_ACCT_SITE_ID 
Left JOIN HZ_PARTY_SITES				HPSF    ON HPSF.PARTY_SITE_ID = HCASF.PARTY_SITE_ID 
left JOIN HZ_PARTIES					HPF		ON HPF.PARTY_ID = HPSF.PARTY_ID 
left JOIN HZ_CUST_ACCOUNTS				HCA		ON HCA.CUST_ACCOUNT_ID = HCAS.CUST_ACCOUNT_ID 
Left Join [PICO_VENTAS].[dbo].[clientes] client On client.[No_] = HPS.PARTY_SITE_NUMBER
left Join [PICO_VENTAS].[dbo].[productos] pro 	ON pro.[No_] = MSIB.SEGMENT1
Left Join MTL_UOM_CONVERSIONS			MUC		On Muc.[UOM_CODE] = OOLA.ORDER_QUANTITY_UOM and Muc.[INVENTORY_ITEM_ID] = OOLA.[INVENTORY_ITEM_ID]
LEFT JOIN OE_REASONS					REA		On REA.HEADER_ID = OOHA.HEADER_ID AND REA.ENTITY_ID = OOLA.LINE_ID
inner JOIN FND_LOOKUP_VALUES			FND		ON FND.LOOKUP_CODE = REA.REASON_CODE AND FND.LANGUAGE = 'ESA'  AND FND.LOOKUP_TYPE = 'CANCEL_CODE'
 
 
WHERE OOLA.FLOW_STATUS_CODE = 'CANCELLED'
and OOLA.ORG_ID = 81
and CONVERT(DATETIME, CONVERT(DATE, OOHA.CREATION_DATE)) > '01-01-2022'
    
    """
    with engine.connect() as conn:
    # Paso 1: Cargar query
        df = pd.read_sql(text(query), conn)
        
        df = df.convert_dtypes()

        # Paso 2: Reemplazar inf y -inf con NaN
        df.replace([np.inf, -np.inf], np.nan, inplace=True)

        # Paso 3: Convertir NaN a None
        df = df.where(pd.notnull(df), None)

        # Convierte el DataFrame a lista de dicts y pásalo por jsonable_encoder
        data = jsonable_encoder(df.to_dict(orient="records"))

        return JSONResponse(content=data)
            
if __name__ == "__main__":
    uvicorn.run("test_api_backend:app", host="0.0.0.0", port=8000, reload=False, log_level="debug",
                workers=1)